// This file is generated by FlutterFire CLI
// You need to run: flutterfire configure
// Or manually add your Firebase configuration

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4P6xPeP2cGe1jphEjp2Y3mnwK6BdkN7s',
    appId: '1:916093655452:android:265b05bd5eb9bf67741059',
    messagingSenderId: '916093655452',
    projectId: 'video-call-app-2993e',
    storageBucket: 'video-call-app-2993e.firebasestorage.app',
  );
}
